### ISSUE TITLE
Embeddedworker.js file uglified

### ISSUE THREAD

**Issue by guirkgumbo** [schul-cloud/riot-embed-sample#2]
I am looking to use this repo but I would like to customize the embedded chat. Is it possible to get an a plain version of the embeddedworker.js file

**Comment by maxklenk** [comment]
Sure, all files used for the embedded chat are generated by compiling this feature branch: https://github.com/schul-cloud/riot-web/tree/feature/embed

**Comment by guirkgumbo** [comment]
Thank you! I attempted to go through the readme for develop but it looks like your riot-web repo https://github.com/maxklenk/riot-web.git doesnt exist anymore? Can I just use riot web as it is as an alternative?

**Comment by maxklenk** [comment]
We moved the repositories to the schul-cloud organization. I have now updated the links in the Readme, thank you for pointing them out.
